name: EssentialFeed CI

on:
  push:
    branches: [ main, master, "feature/**" ]
  pull_request:
    branches: [ main, master, "feature/**" ]

jobs:
  essentialfeed-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SwiftFormat
        run: brew install swiftformat

      - name: Run SwiftFormat (fail if not clean)
        run: |
          swiftformat .
          git diff --exit-code || (echo "SwiftFormat found issues. Please run swiftformat locally." && exit 1)

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2.0' # Changed to specific available version
      - name: Build and test EssentialFeed (macOS)
        run: |
          set -e
          xcodebuild clean build test \
            -project EssentialFeed/EssentialFeed.xcodeproj \
            -scheme "CI_macOS" \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO \
            -sdk macosx \
            -destination "platform=macOS" \
            ONLY_ACTIVE_ARCH=YES
        env:
          NSUnbufferedIO: YES
